USE [master]
GO

/****** Object:  Database [bdtemp2]    Script Date: 04/04/2024 21:52:02 ******/
CREATE DATABASE [bdtemp2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'bdtemp2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.BDSENAC\MSSQL\DATA\bdtemp2.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'bdtemp2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.BDSENAC\MSSQL\DATA\bdtemp2_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [bdtemp2] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [bdtemp2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [bdtemp2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [bdtemp2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [bdtemp2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [bdtemp2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [bdtemp2] SET ARITHABORT OFF 
GO

ALTER DATABASE [bdtemp2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [bdtemp2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [bdtemp2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [bdtemp2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [bdtemp2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [bdtemp2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [bdtemp2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [bdtemp2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [bdtemp2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [bdtemp2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [bdtemp2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [bdtemp2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [bdtemp2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [bdtemp2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [bdtemp2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [bdtemp2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [bdtemp2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [bdtemp2] SET RECOVERY FULL 
GO

ALTER DATABASE [bdtemp2] SET  MULTI_USER 
GO

ALTER DATABASE [bdtemp2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [bdtemp2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [bdtemp2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [bdtemp2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [bdtemp2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [bdtemp2] SET QUERY_STORE = OFF
GO

USE [bdtemp2]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [bdtemp2] SET  READ_WRITE 
GO

